import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const chat = api.post.chat.useQuery({ text: "Hi OpenAI" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Generate with <span className="text-[hsl(280,100%,70%)]">AI</span>
          </h1>
          <p className="text-2xl text-white">
            {chat.data ? chat.data.content : "Loading tRPC query..."}
          </p>
          <button
            className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
            onSubmit={() => {
              window.location.reload();
            }}
          >
            Generate
          </button>
        </div>
      </main>
    </>
  );
}
